.net Classroom Assignments/Day12examples/MVCProjects/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProjects.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrainingDBEntities : DbContext
    {
        public TrainingDBEntities()
            : base("name=TrainingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<RegisterShopping> RegisterShoppings { get; set; }
        public DbSet<UserInfo> UserInfoes { get; set; }
    }
}

.net Classroom Assignments/Day12examples/MVCProjects/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'c:\users\nexwave\documents\visual studio 2015\Projects\day12examples\MVCProjects\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

.net Classroom Assignments/Day12examples/MVCProjects/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

.net Classroom Assignments/Day12examples/MVCProjects/Models/RegisterShopping.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterShopping
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public string membership { get; set; }
        public string shoppingpreference { get; set; }
        public string COD { get; set; }
        public string passw { get; set; }
    }
}

.net Classroom Assignments/Day12examples/MVCProjects/Models/UserInfo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string status { get; set; }
    }
}

.net Classroom Assignments/Day12examples/MVCProjects/Controllers/RegisterShoppingCRUDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MVCProjects.Models;
using System.Web.Mvc;

namespace MVCProjects.Controllers
{
    public class RegisterShoppingCRUDController : Controller
    {
        TrainingDBEntities db = new TrainingDBEntities();
        // GET: RegisterShoppingCRUD
        [HttpGet]
        public ActionResult InsertRegisterShopping()
        {
            return View();
        }
        [HttpPost]
        public ActionResult InsertRegisterShopping(RegisterShopping rs)
        {
            rs.name = Request.Form["txtname"].ToString();
            rs.gender = Request.Form["gender"].ToString();
            rs.membership = Request.Form["ddlmember"].ToString();
            rs.shoppingpreference = Request.Form["shop"].ToString();
            var res =Request.Form["cbcod"].ToString();
            if (res=="false")
                rs.COD = "No";
            else
                rs.COD = "Yes";
            rs.passw = Request.Form["txtpass"].ToString();
            db.RegisterShoppings.Add(rs);
            var result = db.SaveChanges();
            if (result > 0)
                ModelState.AddModelError("", "Data Inserted");
            return View();
        }
        public ActionResult SelectAllRegisterShopping()
        {
            var data = db.RegisterShoppings.ToList();
            return View(data);

        }
        [HttpGet]
        public ActionResult SelectByID()
        {
            var data = new SelectList(db.RegisterShoppings, "Id", "name");
            Session["rsdata"] = data;
            return View();
        }
        [HttpPost]
        public ActionResult SelectByID(string Command)
        {
            int id = int.Parse(Request.Form["ddlid"].ToString());
            if (Command == "SelectByID")
            {
                var data = (db.RegisterShoppings.Where(x => x.Id == id)).SingleOrDefault();
                ViewData["userdata"] = data;
                return View(data);
                
            }
            if(Command=="Update")
            {
                int oldid = int.Parse(Request.Form["txtid"].ToString());
                var olddata = (db.RegisterShoppings.Where(x => x.Id == oldid)).SingleOrDefault();
                olddata.membership = Request.Form["txtmem"].ToString();
                olddata.shoppingpreference = Request.Form["txtshop"].ToString();
                olddata.COD = Request.Form["txtcod"].ToString();
                olddata.passw = Request.Form["txtpass"].ToString();
                var res = db.SaveChanges();
                if (res > 0)
                    ModelState.AddModelError("", "Data Updated");
                return View();
            }
            if(Command=="Delete")
            {
                int oldid = int.Parse(Request.Form["txtid"].ToString());
                var olddata = (db.RegisterShoppings.Where(x => x.Id == oldid)).SingleOrDefault();
                db.RegisterShoppings.Remove(olddata);
                var res = db.SaveChanges();
                if (res > 0)
                    ModelState.AddModelError("", "Data Deleted");
                return View();

            }
            return View();
        }
        [HttpGet]
        public ActionResult SelectAndEdit()
        {
            var data = db.RegisterShoppings.ToList();
            return View(data);
        }
        [HttpGet]
        public ActionResult Update(int id)
        {
            var data = (db.RegisterShoppings.Where(x => x.Id == id)).SingleOrDefault();
            Session["rsdata"] = data;
            return View();
        }
        [HttpPost]
        public ActionResult Update()
        {
            int id = int.Parse(Request.Form["txtid"].ToString());
            var olddata = db.RegisterShoppings.Where(x => x.Id == id).SingleOrDefault();
            olddata.membership = Request.Form["txtmem"].ToString();
            olddata.shoppingpreference = Request.Form["txtshop"].ToString();
            olddata.COD = Request.Form["txtcod"].ToString();
            olddata.passw = Request.Form["txtpass"].ToString();
            var res = db.SaveChanges();
            if (res > 0)
            {
                //Response.Write("Data Updated");
                return RedirectToAction("SelectAndEdit");//redirectiing from controller
            }
            //v that is to redirect after the data is updated
            return View();
        }
    }
}

.net Classroom Assignments/Day12examples/MVCProjects/Views/RegisterShoppingCRUD/InsertRegisterShopping.cshtml
@{
    ViewBag.Title = "InsertRegisterShopping";
}

<h2>InsertRegisterShopping</h2>

@using (Html.BeginForm())
{
    //this is used to display error messages since there is no labels or anything else to display
    @Html.ValidationSummary(true)
    <div>
        <label>Enter Name:</label>
        @Html.TextBox("txtname")
    </div>
    <div>   
        <label>Select Gender</label>
        @Html.RadioButton("gender","Male")Male
        @Html.RadioButton("gender","Female")Female
    </div>
    <div>
        <label>Select Membership</label>
        @Html.DropDownList("ddlmember",new List<SelectListItem> { new SelectListItem { Text = "Free", Value = "Free" }, new SelectListItem { Text = "Paid", Value = "Paid" } },"Select")

    </div>
    <div>
        <label>Select Shopping Preference</label>
        <select id="shop" name="shop" multiple="multiple">
            <option value="Books">Books</option>
            <option value="Apparels">Apparels</option>
            <option value="Cosmetics">Cosmetics</option>
            <option value="Mobiles">Mobiles</option>
            <option value="Kitchen Ware">Kitchen Ware</option>
        </select>
    </div>
    <div>
        <label>Cash On Delivery?</label>
        @Html.CheckBox("cbcod",false)
    </div>
    <div>
        <label>Enter Password</label>
        @Html.Password("txtpass")
    </div>
    <div>
        <input type="submit" value="Insert" />
    </div>
}
@Html.ActionLink("Select All", "SelectAllRegisterShopping");
<br />
@Html.ActionLink("Select By ID","SelectByID")

.net Classroom Assignments/Day12examples/MVCProjects/Views/RegisterShoppingCRUD/SelectAllRegisterShopping.cshtml
@model IEnumerable<MVCProjects.Models.RegisterShopping>
@{
    ViewBag.Title = "SelectAllRegisterShopping";
}

<h2>SelectAllRegisterShopping</h2>
<table border="1">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Gender</th>
        <th>Membership</th>
        <th>Shopping Preference</th>
        <th>COD</th>
        <th>Password</th>
    </tr>
    @foreach(var x in Model)
    {
        <tr>
            <td>@x.Id</td>
            <td>@x.name</td>
            <td>@x.gender</td>
            <td>@x.membership</td>
            <td>@x.shoppingpreference</td>
            <td>@x.COD</td>
            <td>@x.passw</td>
        </tr>
    }
</table>
@Html.ActionLink("Insert New","InsertRegisterShopping")

.net Classroom Assignments/Day12examples/MVCProjects/Views/RegisterShoppingCRUD/SelectAndEdit.cshtml
@model IEnumerable<MVCProjects.Models.RegisterShopping>
@{
    ViewBag.Title = "SelectAndEdit";
}

<h2>SelectAndEdit</h2>
<table border="1">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Gender</th>
        <th>Membership</th>
        <th>Shopping Preference</th>
        <th>COD</th>
        <th>Password</th>
        <th>Edit</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Id</td>
            <td>@x.name</td>
            <td>@x.gender</td>
            <td>@x.membership</td>
            <td>@x.shoppingpreference</td>
            <td>@x.COD</td>
            <td>@x.passw</td>
            <td>@Html.ActionLink("Edit"+@x.Id.ToString(),"Update",new { ID = @x.Id.ToString() })</td>
        </tr>
    }
</table>
@Html.ActionLink("Insert New", "InsertRegisterShopping")

.net Classroom Assignments/Day12examples/MVCProjects/Views/RegisterShoppingCRUD/SelectByID.cshtml
@{
    ViewBag.Title = "SelectByID";
}

<h2>SelectByID</h2>
@using (Html.BeginForm())
{
    <div>
        <label>Select UserDetail</label>
        @Html.DropDownList("ddlid",Session["rsdata"] as SelectList)
    </div>
    <div>
        <input type="submit" value="SelectByID" name="Command" />
    </div>
    if(ViewData["userdata"]!=null)
    {
        MVCProjects.Models.RegisterShopping rs = (MVCProjects.Models.RegisterShopping)ViewData["userdata"];
        <div>
            <label>ID:</label>
            <input type="text" name="txtid" id="txtid" value="@rs.Id" readonly />
        </div>
        <div>
            <label>Name:</label>
            <input type="text" name="txtname" id="txtname" value="@rs.name" readonly/>
        </div>
        <div>
            <label>Gender:</label>
            <input type="text" name="txtgender" id="txtgender" value="@rs.gender" readonly />
        </div>
        <div>
            <label>Membership:</label>
            <input type="text" name="txtmem" id="txtmem" value="@rs.membership" />
        </div>
        <div>
            <label>Shopping Preference:</label>
            <input type="text" name="txtshop" id="txtshop" value="@rs.shoppingpreference" />
        </div>
        <div>
            <label>COD:</label>
            <input type="text" name="txtcod" id="txtcod" value="@rs.COD" />
        </div>
        <div>
            <label>Password:</label>
            <input type="password" name="txtpass" id="txtpass" value="@rs.passw" />
        </div>
        <input type="submit" value="Update" name="Command"/>
        <input type="submit" value="Delete" name="Command" />
    }
}

.net Classroom Assignments/Day12examples/MVCProjects/Views/RegisterShoppingCRUD/Update.cshtml
@{
    ViewBag.Title = "Update";
}

<h2>Update</h2>
@using (Html.BeginForm())
{ 
    if(Session["rsdata"]!=null)
    {
        MVCProjects.Models.RegisterShopping rs = (MVCProjects.Models.RegisterShopping)Session["rsdata"];
        <div>
            <label>Id:</label>
            <input type="text" name="txtid" id="txtid" value="@rs.Id"  readonly/>
        </div>
        <div>
            <label>membership:</label>
            <input type="text" name="txtmem" id="txtmem" value="@rs.membership" />
        </div>
        <div>
            <label>Shopping Preference:</label>
            <input type="text" name="txtshop" id="txtshop" value="@rs.shoppingpreference" />
        </div>
        <div>
            <label>COD:</label>
            <input type="text" name="txtcod" id="txtcod" value="@rs.COD" />
        </div>
        <div>
            <label>password:</label>
            <input type="text" name="txtpass" id="txtpass" value="@rs.passw" />
        </div>
        <div>
            <input type="submit" value="update"  />
        </div>
    }
}

.net Classroom Assignments/Day12examples/MVCProjects/Views/Shared/MasterView.cshtml
<div style="background-color:antiquewhite;font-family:'Berlin Sans FB';text-shadow:20px 12px 2px black;width:auto;height:100px">
    <h1>Register Shopping MVC Application</h1>
</div>
<div style="background-color:whitesmoke;font-family:'Berlin Sans FB';color:lightblue;width:auto;height:auto">
    <table border="1">
        <tr>
            <td>@Html.ActionLink("Insert New","InsertRegisterShopping","RegisterShoppingCRUD")</td>
            <td>@Html.ActionLink("Select All","SelectAllRegisterShopping","RegisterShoppingCRUD")</td>
            <td>@Html.ActionLink("Select By ID","SelectByID","RegisterShoppingCRUD")</td>
            <td>@Html.ActionLink("Select And Edit","SelectAndEdit","RegisterShoppingCRUD")</td>
        </tr>
    </table>
</div>
<div style="background-color:Highlight">
    @RenderBody();
</div>

.net Classroom Assignments/Day12examples/MVCProjects/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>